<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ASMV3 Test Suite - Handtekening-NietAfgewerktMelden</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>24c40955-79fd-42e9-8704-8079bea97313</testSuiteGuid>
   <testCaseLink>
      <guid>19dc374f-5c7a-412f-acc2-ebfd8876c401</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Algemeen/LoginLocalhost</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c219c4d-3a42-4aa3-b468-08c8c5693fd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a761390e-35b4-40a4-8b23-ff80bcd9ad39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46a52aee-78ec-4f50-8151-84767d512d96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff384239-e4e0-442c-9261-45c538c2f2a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/HomeIndex</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>02e41079-389d-433d-8eee-6be5a92283f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/ASMV3/CreateNewRegistratie</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db521c1a-bda1-4304-8ac2-88bf4f6b4463</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb50eda-4320-471b-9fc1-9d697e6f4a04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fada053-09b8-489e-91b9-fd29a5914fd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fc5e1d1-1ae7-47d6-858f-542d73b292fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30fdfd47-0fe6-4c33-8a28-30dce76485cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b22fdfa3-8a6c-487b-a182-b4ab7bfef76f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b89b028-0491-483d-b5ab-f2e022b9e86b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>106cb403-59f3-4493-844d-37719631299a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d36590e8-8c6c-43d6-8137-2495db8f11a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab70dae2-91d9-4281-8497-0ae87bb991bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46a692ae-9f71-4eb9-a802-337597813c14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0b1e21d-fa11-4797-bec1-ccd8c03c78e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/WerkorderOppakken-Handtekening-NietAfgewerktMelden</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd9102cf-ca39-4622-a05c-7afa8b0ec1e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40966406-083b-48df-b174-975aa1b0b926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c57f82e-121a-46e4-bcd3-cb80fe49f78d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb78d4fc-bca0-4649-b20e-4b62ff71222a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79fbb495-2130-48ce-9d41-db95560ca081</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78e32f9-0b0f-45db-9379-04d85b56eac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9623350d-7bed-4728-9e8f-b7e0428c6f82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90934c16-382f-46a9-96dd-e10b89ef63c4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
