<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ASMV3 Test Suite - Geparkeerde Werkorder-Handtekening-NietAfgewerktMelden</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ad61d51b-f23e-4927-bc25-d9ba305aa271</testSuiteGuid>
   <testCaseLink>
      <guid>19dc374f-5c7a-412f-acc2-ebfd8876c401</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Algemeen/LoginLocalhost</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c219c4d-3a42-4aa3-b468-08c8c5693fd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a761390e-35b4-40a4-8b23-ff80bcd9ad39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46a52aee-78ec-4f50-8151-84767d512d96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff384239-e4e0-442c-9261-45c538c2f2a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/HomeIndex</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e0b1e21d-fa11-4797-bec1-ccd8c03c78e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/GeparkeerdeWerkorderOppakken-Handtekening-NietAfgewerktMelden</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd9102cf-ca39-4622-a05c-7afa8b0ec1e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40966406-083b-48df-b174-975aa1b0b926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c57f82e-121a-46e4-bcd3-cb80fe49f78d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb78d4fc-bca0-4649-b20e-4b62ff71222a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79fbb495-2130-48ce-9d41-db95560ca081</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78e32f9-0b0f-45db-9379-04d85b56eac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9623350d-7bed-4728-9e8f-b7e0428c6f82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90934c16-382f-46a9-96dd-e10b89ef63c4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
