<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ASMV3 Test Suite - Geparkeerde Werkorder-Handtekening-Gereedmelden</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-20T11:23:11</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4632a8c7-3e37-4cda-b148-c5488297da4d</testSuiteGuid>
   <testCaseLink>
      <guid>19dc374f-5c7a-412f-acc2-ebfd8876c401</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Algemeen/LoginLocalhost</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c219c4d-3a42-4aa3-b468-08c8c5693fd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a761390e-35b4-40a4-8b23-ff80bcd9ad39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46a52aee-78ec-4f50-8151-84767d512d96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff384239-e4e0-442c-9261-45c538c2f2a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/HomeIndex</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>42c6ef95-73e4-47f9-a6c3-4fc41c95356f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/Geparkeerde-Werkorder-Handtekening-Gereedmelden</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8ec1707-738c-4c0a-80ef-9207ce297ed1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2ab2939-80f8-41e6-af0f-9dbb424f6835</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00004094-379f-4f8c-ad1f-f0c33f36a90a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdd046f3-29d5-4591-a418-7483a7ba84d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bfa095d-3d64-47ce-9d61-b75909d45698</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e90aa364-0f0c-4ada-b6cf-c3b1986ff8bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e9675e-41af-438d-867d-cb6eb345d987</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72ade85c-5429-4166-b78c-d303f6cdd700</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
