<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ASMV3 Test Suite - Geparkeerde Werkorder-Niet Afgewerkt melden</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>db3c86c4-e7ff-4604-815a-a62ab3acccdb</testSuiteGuid>
   <testCaseLink>
      <guid>19dc374f-5c7a-412f-acc2-ebfd8876c401</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Algemeen/LoginLocalhost</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c219c4d-3a42-4aa3-b468-08c8c5693fd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a761390e-35b4-40a4-8b23-ff80bcd9ad39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46a52aee-78ec-4f50-8151-84767d512d96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff384239-e4e0-442c-9261-45c538c2f2a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/HomeIndex</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>42c6ef95-73e4-47f9-a6c3-4fc41c95356f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/Geparkeerde-Werkorder-NietAfgewerktMelden</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba0846e0-754d-4248-b095-4651da640b38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e876b854-e369-477f-a681-defd5cda63b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f12b4449-d094-47d2-9ca2-5519b29a68cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55893cbe-fe9b-44ba-8092-2b8316e6ee2f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
