<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ASMV3 Test Suite - Geparkeerde Werkorder-Handtekening-Opslaan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cc302b7b-5456-483d-a8ec-a9f2f8dbd6b9</testSuiteGuid>
   <testCaseLink>
      <guid>19dc374f-5c7a-412f-acc2-ebfd8876c401</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Algemeen/LoginLocalhost</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c219c4d-3a42-4aa3-b468-08c8c5693fd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a761390e-35b4-40a4-8b23-ff80bcd9ad39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46a52aee-78ec-4f50-8151-84767d512d96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff384239-e4e0-442c-9261-45c538c2f2a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/HomeIndex</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5aa582f9-dea4-4a87-aee0-e587029bfbd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ASMV3/GeparkeerdeWerkorderOppakken-Handtekening-Opslaan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e59d48ec-a878-4371-ade9-f95042674de5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc8198c8-9ed9-432b-b031-c8316810825d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60a30164-39c9-42ca-b3ea-a3a0d047d471</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1ee81db-9c1c-469a-9972-38a964b61d58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ccb38e7-966a-42bc-846d-c14013830273</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5de5b2a3-66f4-4ae4-af14-a80feff54372</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b091322-ee39-4b1b-b610-a69fc9b7c4cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74a98e9f-eebb-47a5-91fa-044e46ad5fc9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
