<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contract</name>
   <tag></tag>
   <elementGuidId>aa8355a5-ec95-4153-95c7-654211eac60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-test-id=&quot;contract-input-field&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
