<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bedrijf</name>
   <tag></tag>
   <elementGuidId>7fd57d8f-ed99-4c0b-924b-c1f46f5bda7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-test-id=&quot;bedrijf-input-field&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
