<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notify_Buttons</name>
   <tag></tag>
   <elementGuidId>a1b54c33-f8d1-453c-8d1c-ecb4d8c95760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;noty_buttons&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
