<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_InstallatieSearchItem</name>
   <tag></tag>
   <elementGuidId>0af07902-59f5-47a8-80dc-48990d6841de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#set-currentitem-installatie-searchdialog</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
