<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DossierSearchItem</name>
   <tag></tag>
   <elementGuidId>398385ef-1a2b-45b4-968c-ebab3c49e738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#set-currentitem-dossier-searchdialog</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
