<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpenGlobalMenuNav</name>
   <tag></tag>
   <elementGuidId>4d2409e7-9458-40a7-a3ff-acb4dece5704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-menu-navbutton-menu</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
