<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ProjectMateriaalVerwijderen</name>
   <tag></tag>
   <elementGuidId>a4c60066-02a3-4f39-990f-222e4b091075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[@class=&quot;btn btn-default&quot;]		[count(. | //button[(text() = 'Verwijderen' or . = 'Verwijderen') and @type = 'button']) = count(//button[(text() = 'Verwijderen' or . = 'Verwijderen') and @type = 'button'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verwijderen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>[@class=&quot;btn btn-default&quot;]		</value>
   </webElementProperties>
</WebElementEntity>
