<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wizardStep_Time</name>
   <tag></tag>
   <elementGuidId>a562913e-1b3d-4b69-b7ab-9478416473aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-test-id=&quot;workorder-options-clickhandler-time&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
