<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_WisHandtekening</name>
   <tag></tag>
   <elementGuidId>435dd719-d666-4729-9da5-a87919e5f239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-test-id=&quot;clear-signature-canvas&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
