<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RedenNietAfgemeld</name>
   <tag></tag>
   <elementGuidId>2502fdae-cb4b-4ca7-a75b-159a2e1493ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#set-currentitem-dossier-searchdialog</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;general-field-dialog&quot;]/div/div/div[2]/div/div/form-group/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;general-field-dialog&quot;]/div/div/div[2]/div/div/form-group/div/select</value>
   </webElementProperties>
</WebElementEntity>
