<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppHome</name>
   <tag></tag>
   <elementGuidId>c6cad879-bacf-4c94-8827-823872f8b628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-menu-navbutton-home</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
