<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GotoWerkorders</name>
   <tag></tag>
   <elementGuidId>6a9e294d-85ea-4938-9349-54a8518f8f29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-test-id=&quot;asm-home-index-goto-orders&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
