<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-Password</name>
   <tag></tag>
   <elementGuidId>eec4331c-60a6-4144-a48e-5ca5a559d124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CurrentPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
